name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        working-directory: java_sqs_client
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/java-sqs-client:latest .

      - name: Tag Docker image with Git SHA
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/java-sqs-client:latest ${{ secrets.DOCKER_HUB_USERNAME }}/java-sqs-client:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/java-sqs-client:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/java-sqs-client:${{ github.sha }}